### ISSUE TITLE
#to_h serializes all instance methods

### ISSUE THREAD

**Issue by nandosola** [stitchfix/immutable-struct#4]
Hi,

I'd like to be able to use standard Ruby methods in my `ImmutableStruct`. I'm currently having problems with this one:

```ruby
it "should allow #== method to be overriden" do
  klass = ImmutableStruct.new(:id, :flappy) do
    def ==(other)
      self.id == other.id
    end
  end
  instance = klass.new(id: 1, flappy: 'bird')
  instance.to_h.should == {id: 1, flappy: 'bird'}
end
```

Just because `#to_h` [processes all instance methods](https://github.com/stitchfix/immutable-struct/blob/df5b280520abcac144e46dde4287264a50df7316/lib/immutable-struct.rb#L72), regardless of their intent and it fails when calling methods with arity > 0:

```
1) ImmutableStruct to_h should allow #== method to be overriden
     Failure/Error: def ==(other)
     ArgumentError:
       wrong number of arguments (0 for 1)
     # ./spec/immutable_struct_spec.rb:128:in `=='
     # ./lib/immutable-struct.rb:72:in `block (3 levels) in new'
     # ./lib/immutable-struct.rb:72:in `each'
     # ./lib/immutable-struct.rb:72:in `inject'
     # ./lib/immutable-struct.rb:72:in `block (2 levels) in new'
     # ./spec/immutable_struct_spec.rb:133:in `block (3 levels) in <top (required)>'
```

Moreover, if the user decides to implement `#to_s`, domain-related logic or even a conversion method, these would be serialized as well with unexpected consequences depending on their arity.

IMO this issue raises an interesting question: is it really necessary to serialize all instance methods? In Ruby's [`Struct#to_hash`](http://ruby-doc.org/core-2.2.0/Struct.html#method-i-to_h) only the struct members (ie. those defined in the constructor) are serialized. So I'd expect `ImmutableStruct` to behave in the same way.

If this is OK with you I'd be happy to submit a PR.

Kind regards,
//nando

**Comment by davetron5000** [comment]
I would agree that it should only be including 0-arity methods in the implementation of `to_h`.

I'm not sure that it should only include those attributes defined in the class constructor though.  The use case for this class is to create a data container or read-only struct, so creating methods on it that should not be part of `to_h` goes counter to its mandate.

That said, I'm open to it being configurable, like maybe:

```ruby
not_serialized def super_secret
  "foo"
end
```

or something.  Might help to know more about your use case.

**Comment by nandosola** [comment]
IMHO this kind of "annotations" would hide the true meaning of `ImmutableStruct#to_h`. In my use case I'd expect a similar behavior to that of Ruby's `Struct` or any other encapsulation of state (ie. classes). If for `ImmutableStruct` 0-arity instance methods are state and not messages, then of course I'd expect the returning value of these methods to be serialized as well. But in this case then the statement from the README _"you can also treat the interior as a normal class definition"_ wouldn't be correct because in any normal class definition in Ruby the user can override at least `#==`, `#<=>`, `#to_s`, or even `#to_h`. And define any other methods as well without having to "upgrade" to vanilla Ruby classes.

TBH in my use case I don't need derived attributes. I can deserialize the hash into the original object and invoke the method again. But another way of dealing with this situation could be that `ImmutableStruct#to_h` just took into account the (0-arity) operations that are passed to a `derived` class method:

```ruby
klass = ImmutableStruct.new(:foo, :bar) do
        derived(sum: ->{ foo + bar })
        derived(sub: ->{ foo - bar })
        #…
        def ==(other)
          #…
        end
        def method(a_baz)
           #…
        end
        def to_s
          #…
        end
      end
#…
klass.new(foo:2, bar:2)
{
    :foo => 2,
    :bar => 2,
    :sum => 4,
    :sub => 0
}
```

This could be a good one, but IMO it crosses the border into DSL land (which could be just fine). Please don't get me wrong: I love the simplicity of this gem and maybe the importance of these derived attributes is overstated or I just don't understand the need for them.

**Comment by davetron5000** [comment]
Once the bug is fixed that attempts to use nonzero-arity methods in `to_h`, there is nothing preventing you overriding methods like `==` and `>`, since they are not zero arity.

So we are really talking about: "should zero-arity methods be included in `to_h` by default".  Since that is the behavior now, I have to insist that the answer is "Yes", because changing the default behavior doesn't seem like a worthwhile breaking change.

So the question is: how can this behavior be avoided if someone is creating 0-arity methods that they don't want in `to_h`? i.e. can your use-case be satisfied without introducing a breaking change.

The simplest solution I can think of is as follows:

* Define `attributes_to_h` to return a hash of only those attributes defined in the class constructor
* Define `derived_to_h` to return a hash of the results all 0-arity methods that are not attributes defined in the class constructor
* Define `to_h` to merge `attributes_to_h` and `derived_to_h`

Then, if you don't wish to have the default implementation of `to_h`, you have a few options:

* alias it to `attributes_to_h`
* override it completely
* use `attribtues_to_h` and `derived_to_h` however you like to pick and choose

This would be backwards compatible, not involve DSL magic, and result in our `ImmutableStruct` instances still being pretty vanilla ruby classes.  

How does that sound?

**Comment by nandosola** [comment]
:+1: 

My first internal workaround was more or less the same as the one you've just proposed. I totally understand the backwards compatibility issues. So yes: I can live with that way of doing things in `ImmutableStruct`, as long as it's well documented (at least now we've got an issue for that).

I'll update my PR ASAP with your proposal, if that's OK.
